### ISSUE TITLE
Feature: Add doctor availability date and time

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6968]
**Is your feature request related to a problem? Please describe.**

Currently we are not recording doctors availability in a facility based on a date and time

**Describe the solution you'd like**

- [ ] Add a feature to mark the availability of a doctor
- [ ] Should support multiple time slots in a day, and multiple days of the week.
- [ ] Should disallow creating conflicting/overlapping entires.
- [ ] The availability record should be optionally linked to a location that belongs to their home facility.
- [ ] A user should be able to set or edit only their availability.
- [ ] DistrictAdmin and above should be able to set or edit all doctors' availability.
- [ ] The option should support marking multiple days and times, or all day. 

For example, if a user is available on Monday from 2:00 to 4:00 PM, and Tuesday from 3:00 to 4:00 PM, we should be able to mark it or specify day availability without a specific time. Alternatively, there can be an option to specify availability all day in case the user does not want to mention specific times or days of availability.

**Comment by rithviknishad** [comment]
@gigincg / @aparnacoronasafe 

1. Should the doctor availability record be optionally or mandatorily related to a Facility or a Location?

2. If yes (1), should they be allowed to be available in multiple facility/locations at the same time?

**Comment by rithviknishad** [comment]
Dropping a mock UI here for suggestions

<img width="1697" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/8334fb6b-a96b-44df-b9d1-863c62078683">

**Comment by rithviknishad** [comment]
Dropping a draft model schema here:

```yaml
UserAvailabilityModel:
  # relations
  user: ForeignKey(UserModel.id)
  location: ForeignKey(AssetLocationModel.id, null=True) # Any one of location or facility or none in final
  facility: ForeignKey(Facility.id, null=True) # Any one of location or facility or none in final

  # fields
  day_of_week: SmallIntegerField(choices=[sun, mon, tue, wed, thu, fri, sat], db_index=True)
  start_time: TimeField(db_index=True)
  end_time: TimeField(db_index=True)

  # meta fields
  removed_at: DateTimeField(auto_delete_now=True, null=True)
```

Indexes on fields `day_of_week`, `start_time`, `end_time` fields in addition to `user`, `location`, `facility` foreign keys.
